[package]
name = "sourmash_plugin_branchwater"
version = "0.9.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sourmash_plugin_branchwater"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module", "anyhow"] }
rayon = "1.10.0"
serde = { version = "1.0.213", features = ["derive"] }
sourmash = { version = "0.17.0", features = ["branchwater"] }
serde_json = "1.0.132"
niffler = "2.4.0"
log = "0.4.22"
env_logger = { version = "0.11.5" }
simple-error = "0.3.1"
anyhow = "1.0.93"
zip = { version = "2.0", default-features = false }
tempfile = "3.14"
needletail = "0.5.1"
csv = "1.3.1"
camino = "1.1.9"
glob = "0.3.1"
rustworkx-core = "0.15.1"
streaming-stats = "0.2.3"

[dev-dependencies]
assert_cmd = "2.0.16"
assert_matches = "1.5.0"
predicates = "3.1.2"
tempfile = "3.14.0"

[profile.release]
#target-cpu=native
#lto = "thin"
opt-level = 3
