[package]
name = "pyo3-branchwater"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyo3_branchwater"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.2", features = ["extension-module", "anyhow"] }
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
sourmash = { git = "https://github.com/sourmash-bio/sourmash", "rev" = "ff1092f8f366339caa59d7203f623813228f4356" }
serde_json = "1.0.79"
niffler = "2.4.0"
log = "0.4.14"
env_logger = "0.10.0"
simple-error = "0.3.0"
anyhow = "1.0.75"
zip = "0.6"
tempfile = "3.8"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_matches = "1.5.0"
predicates = "3.0.3"
tempfile = "3.3.0"

[profile.release]
#target-cpu=native
lto = "thin"
opt-level = 3
