[package]
name = "pyo3-branchwater"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyo3_branchwater"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
sourmash = "0.11.0"
clap = { version = "3.1.0", features = ["derive"] }
serde_json = "1.0.79"
niffler = "2.4.0"
log = "0.4.14"
env_logger = "0.9.0"
simple-error = "0.3.0"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_matches = "1.5.0"
predicates = "2.1.1"
tempfile = "3.3.0"

[profile.release]
#target-cpu=native
lto = "thin"
opt-level = 3
