[package]
name = "sourmash_plugin_branchwater"
version = "0.9.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sourmash_plugin_branchwater"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "anyhow"] }
rayon = "1.10.0"
serde = { version = "1.0.198", features = ["derive"] }
sourmash = { version = "0.13.1", features = ["branchwater"] }
serde_json = "1.0.116"
niffler = "2.4.0"
log = "0.4.14"
env_logger = "0.11.3"
simple-error = "0.3.0"
anyhow = "1.0.82"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
tempfile = "3.10"
needletail = "0.5.1"
csv = "1.3.0"
camino = "1.1.6"
glob = "0.3.1"
rustworkx-core = "0.14.2"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_matches = "1.5.0"
predicates = "3.1.0"
tempfile = "3.10.0"

[profile.release]
#target-cpu=native
lto = "thin"
opt-level = 3
