[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "pymagsearch"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


[project.scripts]
"pymagsearch" = "pymagsearch.__main__:main"

[project.entry-points."sourmash.cli_script"]
magsearch = "pymagsearch.sourmash_plugin:Magsearch_Extension"

[tool.maturin]
python-source = "python"
