name: "maturin build"
on:
  pull_request:
  push:
    branches: [latest]
jobs:
  mamba:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install latest stable rust
      uses: actions-rs/toolchain@v1
      with:
         toolchain: stable
         override: true
         components: rustfmt, clippy

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: cache rust
      uses: Swatinem/rust-cache@v2

    - name: cache conda
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: setup conda
      uses: conda-incubator/setup-miniconda@11b562958363ec5770fef326fe8ef0366f8cbf8a
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge,bioconda
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        mamba-version: "*"
        activate-environment: sourmash_dev
        auto-activate-base: false
        use-only-tar-bz2: true

    - name: install dependencies
      shell: bash -l {0}
      run: mamba install git compilers maturin pytest pandas

    - name: build
      shell: bash -l {0}
      run: make

    - name: test
      shell: bash -l {0}
      run: pytest
