name: "maturin build"
on:
  pull_request:
  push:
    branches: [latest]
jobs:
  mamba:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install latest stable rust
      uses: dtolnay/rust-toolchain@stable
      with:
         toolchain: stable
         override: true
         components: rustfmt, clippy

    - name: Run cargo fmt
      run: cargo fmt --all -- --check --verbose

    - name: cache rust
      uses: Swatinem/rust-cache@v2

    - name: cache conda
      uses: actions/cache@v4
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: setup conda
      uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge,bioconda
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        mamba-version: "*"
        activate-environment: sourmash_dev
        auto-activate-base: false
        use-only-tar-bz2: true

    - name: install dependencies
      shell: bash -l {0}
      run: mamba install git compilers maturin pytest pandas crossenv libclang clangdev

    - name: build
      shell: bash -l {0}
      run: make

    - name: test
      shell: bash -l {0}
      run: pytest
